numero = int(input("Digite um número: "))
print("-"*15)
print("TABUADA DO {}".format(numero))
print(numero, "x 1 = {}".format(numero * 1))
print(numero, "x 2 = {}".format(numero * 2))
print(numero, "x 3 = {}".format(numero * 3))
print(numero, "x 4 = {}".format(numero * 4))
print(numero, "x 5 = {}".format(numero * 5))
print(numero, "x 6 = {}".format(numero * 6))
print(numero, "x 7 = {}".format(numero * 7))
print(numero, "x 8 = {}".format(numero * 8))
print(numero, "x 9 = {}".format(numero * 9))
print(numero, "x 10 = {}".format(numero * 10))
print("-"*15)
